# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './designer/LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1824, 1452)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleLabel = QtWidgets.QLabel(Dialog)
        self.titleLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Karumbi")
        font.setPointSize(100)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.titleLabel.setFont(font)
        self.titleLabel.setScaledContents(False)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_3.addWidget(self.titleLabel)
        self.userTileFrame = QtWidgets.QFrame(Dialog)
        self.userTileFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.userTileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.userTileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userTileFrame.setObjectName("userTileFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.userTileFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3.addWidget(self.userTileFrame)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(857, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.signUpBtn = QtWidgets.QPushButton(self.frame_3)
        self.signUpBtn.setObjectName("signUpBtn")
        self.horizontalLayout_3.addWidget(self.signUpBtn)
        spacerItem1 = QtWidgets.QSpacerItem(856, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(792, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.errorLabel = QtWidgets.QLabel(self.frame)
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout_10.addWidget(self.errorLabel)
        spacerItem3 = QtWidgets.QSpacerItem(791, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.frame)
        self.signUpFrame = QtWidgets.QFrame(Dialog)
        self.signUpFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.signUpFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signUpFrame.setObjectName("signUpFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.signUpFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(573, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.frame_5 = QtWidgets.QFrame(self.signUpFrame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(self.frame_4)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameField = QtWidgets.QLineEdit(self.frame_4)
        self.usernameField.setObjectName("usernameField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameField)
        self.genderLabel = QtWidgets.QLabel(self.frame_4)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.genderComboBox = QtWidgets.QComboBox(self.frame_4)
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.genderComboBox)
        self.birthdayLabel = QtWidgets.QLabel(self.frame_4)
        self.birthdayLabel.setObjectName("birthdayLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.birthdayLabel)
        self.birthdayEditor = QtWidgets.QDateEdit(self.frame_4)
        self.birthdayEditor.setObjectName("birthdayEditor")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.birthdayEditor)
        self.passwordLabel = QtWidgets.QLabel(self.frame_4)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.emptyLabel = QtWidgets.QLabel(self.frame_4)
        self.emptyLabel.setText("")
        self.emptyLabel.setObjectName("emptyLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.emptyLabel)
        self.confirmNewPasswordField = QtWidgets.QLineEdit(self.frame_4)
        self.confirmNewPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmNewPasswordField.setObjectName("confirmNewPasswordField")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.confirmNewPasswordField)
        self.newPasswordField = QtWidgets.QLineEdit(self.frame_4)
        self.newPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordField.setObjectName("newPasswordField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.newPasswordField)
        self.horizontalLayout_9.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.nevermindBtn_2 = QtWidgets.QPushButton(self.frame_6)
        self.nevermindBtn_2.setObjectName("nevermindBtn_2")
        self.horizontalLayout_4.addWidget(self.nevermindBtn_2)
        self.createAccountBtn = QtWidgets.QPushButton(self.frame_6)
        self.createAccountBtn.setObjectName("createAccountBtn")
        self.horizontalLayout_4.addWidget(self.createAccountBtn)
        spacerItem6 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.frame_6)
        self.horizontalLayout_5.addWidget(self.frame_5)
        spacerItem7 = QtWidgets.QSpacerItem(573, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_3.addWidget(self.signUpFrame)
        self.signInFrame = QtWidgets.QFrame(Dialog)
        self.signInFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.signInFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signInFrame.setObjectName("signInFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.signInFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(608, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.frame_2 = QtWidgets.QFrame(self.signInFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.passwordField = QtWidgets.QLineEdit(self.frame_10)
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordField.setObjectName("passwordField")
        self.horizontalLayout_8.addWidget(self.passwordField)
        spacerItem10 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.keepSignedInBtn = QtWidgets.QRadioButton(self.frame_9)
        self.keepSignedInBtn.setObjectName("keepSignedInBtn")
        self.horizontalLayout_7.addWidget(self.keepSignedInBtn)
        spacerItem12 = QtWidgets.QSpacerItem(86, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.nevermindBtn_1 = QtWidgets.QPushButton(self.frame_8)
        self.nevermindBtn_1.setObjectName("nevermindBtn_1")
        self.horizontalLayout_2.addWidget(self.nevermindBtn_1)
        self.signInBtn = QtWidgets.QPushButton(self.frame_8)
        self.signInBtn.setObjectName("signInBtn")
        self.horizontalLayout_2.addWidget(self.signInBtn)
        spacerItem14 = QtWidgets.QSpacerItem(96, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.horizontalLayout_6.addWidget(self.frame_2)
        spacerItem15 = QtWidgets.QSpacerItem(557, 249, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.verticalLayout_3.addWidget(self.signInFrame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleLabel.setText(_translate("Dialog", "XenoTrade"))
        self.signUpBtn.setText(_translate("Dialog", "Sign Up"))
        self.errorLabel.setText(_translate("Dialog", "ErrorLabel"))
        self.usernameLabel.setText(_translate("Dialog", "Username:"))
        self.usernameField.setPlaceholderText(_translate("Dialog", "Johnny1800"))
        self.genderLabel.setText(_translate("Dialog", "Gender:"))
        self.genderComboBox.setItemText(0, _translate("Dialog", "male"))
        self.genderComboBox.setItemText(1, _translate("Dialog", "female"))
        self.birthdayLabel.setText(_translate("Dialog", "Birthday:"))
        self.passwordLabel.setText(_translate("Dialog", "Password:"))
        self.confirmNewPasswordField.setPlaceholderText(_translate("Dialog", "confirm password"))
        self.newPasswordField.setPlaceholderText(_translate("Dialog", "password"))
        self.nevermindBtn_2.setText(_translate("Dialog", "Nevermind"))
        self.createAccountBtn.setText(_translate("Dialog", "Create Account"))
        self.passwordField.setPlaceholderText(_translate("Dialog", "Password"))
        self.keepSignedInBtn.setText(_translate("Dialog", "Keep me signed in"))
        self.nevermindBtn_1.setText(_translate("Dialog", "Nevermind"))
        self.signInBtn.setText(_translate("Dialog", "Sign In"))

